version: "3.7"
services:
  # servicio 1: La base de datos
  serv-mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    ports:
      # puerto externo: puerto interno
      - 3306:3306
    volumes:
      - E:/projects/docker/databases/mysql_3.7/schemas:/var/lib/mysql
    networks:
      - laravel_prod_net

  # servicio 2: La instalación de apache
  serv-laravel:
    build:
      # context: de donde se va a recuperar la configuración para la instalación
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8200:80
    volumes:
      - ./:/var/www/
      - ./public:/var/www/html
    networks:
      - laravel_prod_net
    # depends_on indica que se cree primero la bd (servicio 1)
    depends_on:
      - serv-mysql

# se confirman los volumenes
volumes:
  example-prod:  # carpeta ./example-prod
  database:      # carpeta E:/projects/docker/databases/mysql_3.7/schemas

networks:
  laravel_prod_net: